name: coconut_lib
description: This is a library for Coconut Vault, Coconut Wallet.
version: 0.6.0
repository: https://github.com/noncelab/coconut_lib.git

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  hex: ^0.2.0
  pointycastle: ^3.9.1
  convert: ^3.1.1
  bech32: ^0.2.2
  http: ^1.2.1
  json_annotation: ^4.9.0
  objectbox: ^4.0.1
  bech32m_i: ^0.2.2
  decimal: ^3.0.2
  flat_buffers: ^23.5.26

dev_dependencies:
  faker: ^2.1.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  lints: ^3.0.0
  objectbox_generator: ^4.0.1
  test: ^1.24.0
  mockito: ^5.4.4
