// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import '../../src/objectbox/entity/address.entity.dart';
import '../../src/objectbox/entity/address_book.entity.dart';
import '../../src/objectbox/entity/balance.entity.dart';
import '../../src/objectbox/entity/block_header.entity.dart';
import '../../src/objectbox/entity/custom_id.entity.dart';
import '../../src/objectbox/entity/transaction.entity.dart';
import '../../src/objectbox/entity/utxo.entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 8014993787536735417),
      name: 'AddressBookEntity',
      lastPropertyId: const obx_int.IdUid(6, 5189847368964674514),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 9018273351750162496),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2886631135505728633),
            name: 'walletId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(1, 7530675535564914145)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1116970478782687556),
            name: 'usedReceiveIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6548122699419269517),
            name: 'usedChangeIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5077326793942183402),
            name: 'maxReceiveIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5189847368964674514),
            name: 'maxChangeIndex',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'receiveList',
            srcEntity: 'AddressEntity',
            srcField: 'receiveBook'),
        obx_int.ModelBacklink(
            name: 'changeList',
            srcEntity: 'AddressEntity',
            srcField: 'changeBook')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7130450186900341681),
      name: 'AddressEntity',
      lastPropertyId: const obx_int.IdUid(8, 6168532388273860245),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1456593993712733715),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1200313722705447774),
            name: 'address',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 2455283036361249485)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6074489665236424460),
            name: 'isUsed',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 9003340150256650687),
            name: 'derivationPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1189679109853529460),
            name: 'index',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(3, 5596150059936823979)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3549517773112521970),
            name: 'amount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5634531446040445455),
            name: 'receiveBookId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 1753740113229870902),
            relationTarget: 'AddressBookEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6168532388273860245),
            name: 'changeBookId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 2116507484159235642),
            relationTarget: 'AddressBookEntity')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7586459980808972662),
      name: 'BalanceEntity',
      lastPropertyId: const obx_int.IdUid(4, 371001103305686170),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6814199509036821149),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8551117140248239305),
            name: 'walletId',
            type: 6,
            flags: 32808,
            indexId: const obx_int.IdUid(6, 6474953575629998843)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4342717748033023612),
            name: 'confirmed',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 371001103305686170),
            name: 'unconfirmed',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 1371990766299979689),
      name: 'BlockHeaderEntity',
      lastPropertyId: const obx_int.IdUid(4, 7620140504494558136),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3500689317422311880),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2389683595786584327),
            name: 'height',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(7, 5468623615300107141)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5791326655516510145),
            name: 'timestamp',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7620140504494558136),
            name: 'header',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 4706518915769206143),
      name: 'CustomIdEntity',
      lastPropertyId: const obx_int.IdUid(3, 525226761870863632),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 115901226979030191),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2025437576425438629),
            name: 'entityName',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(8, 3859591650777500417)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 525226761870863632),
            name: 'customId',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(9, 6561477819505586655))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 4335713203424357164),
      name: 'TransactionEntity',
      lastPropertyId: const obx_int.IdUid(8, 2743695591706483586),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3335909856317327488),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3835583791090326223),
            name: 'walletId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(10, 2580628522399747429)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 876032712767481610),
            name: 'txHash',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(11, 6307326506000754331)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5625483063069502915),
            name: 'txString',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6384313623997119364),
            name: 'timestamp',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2865605208915271759),
            name: 'height',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7329413251007492970),
            name: 'prevTxStringList',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2743695591706483586),
            name: 'memo',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 6112481751129783907),
      name: 'UtxoEntity',
      lastPropertyId: const obx_int.IdUid(9, 6449897511216529168),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3478129291886252075),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4687449592441511897),
            name: 'walletId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(12, 4214120009539554081)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2539962844122634885),
            name: 'amount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8236418464128217022),
            name: 'txHash',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(13, 6159233044071635503)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8204335300286672763),
            name: 'index',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4007365242377324754),
            name: 'txString',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 544014155374412101),
            name: 'derivationPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8781147872030346345),
            name: 'timestamp',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(14, 6326529465112002666)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6449897511216529168),
            name: 'height',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(15, 7947996639552529511))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) {
  return obx.Store(getObjectBoxModel(),
      directory: directory,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 6112481751129783907),
      lastIndexId: const obx_int.IdUid(15, 7947996639552529511),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AddressBookEntity: obx_int.EntityDefinition<AddressBookEntity>(
        model: _entities[0],
        toOneRelations: (AddressBookEntity object) => [],
        toManyRelations: (AddressBookEntity object) => {
              obx_int.RelInfo<AddressEntity>.toOneBacklink(7, object.id,
                      (AddressEntity srcObject) => srcObject.receiveBook):
                  object.receiveList,
              obx_int.RelInfo<AddressEntity>.toOneBacklink(8, object.id,
                      (AddressEntity srcObject) => srcObject.changeBook):
                  object.changeList
            },
        getId: (AddressBookEntity object) => object.id,
        setId: (AddressBookEntity object, int id) {
          object.id = id;
        },
        objectToFB: (AddressBookEntity object, fb.Builder fbb) {
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.walletId);
          fbb.addInt64(2, object.usedReceiveIndex);
          fbb.addInt64(3, object.usedChangeIndex);
          fbb.addInt64(4, object.maxReceiveIndex);
          fbb.addInt64(5, object.maxChangeIndex);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final walletIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final object = AddressBookEntity(walletId: walletIdParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..usedReceiveIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..usedChangeIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..maxReceiveIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..maxChangeIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          obx_int.InternalToManyAccess.setRelInfo<AddressBookEntity>(
              object.receiveList,
              store,
              obx_int.RelInfo<AddressEntity>.toOneBacklink(7, object.id,
                  (AddressEntity srcObject) => srcObject.receiveBook));
          obx_int.InternalToManyAccess.setRelInfo<AddressBookEntity>(
              object.changeList,
              store,
              obx_int.RelInfo<AddressEntity>.toOneBacklink(8, object.id,
                  (AddressEntity srcObject) => srcObject.changeBook));
          return object;
        }),
    AddressEntity: obx_int.EntityDefinition<AddressEntity>(
        model: _entities[1],
        toOneRelations: (AddressEntity object) =>
            [object.receiveBook, object.changeBook],
        toManyRelations: (AddressEntity object) => {},
        getId: (AddressEntity object) => object.id,
        setId: (AddressEntity object, int id) {
          object.id = id;
        },
        objectToFB: (AddressEntity object, fb.Builder fbb) {
          final addressOffset = fbb.writeString(object.address);
          final derivationPathOffset = fbb.writeString(object.derivationPath);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, addressOffset);
          fbb.addBool(2, object.isUsed);
          fbb.addOffset(3, derivationPathOffset);
          fbb.addInt64(4, object.index);
          fbb.addInt64(5, object.amount);
          fbb.addInt64(6, object.receiveBook.targetId);
          fbb.addInt64(7, object.changeBook.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final isUsedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final derivationPathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final indexParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final amountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final object = AddressEntity(
              address: addressParam,
              isUsed: isUsedParam,
              derivationPath: derivationPathParam,
              index: indexParam,
              amount: amountParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.receiveBook.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.receiveBook.attach(store);
          object.changeBook.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.changeBook.attach(store);
          return object;
        }),
    BalanceEntity: obx_int.EntityDefinition<BalanceEntity>(
        model: _entities[2],
        toOneRelations: (BalanceEntity object) => [],
        toManyRelations: (BalanceEntity object) => {},
        getId: (BalanceEntity object) => object.id,
        setId: (BalanceEntity object, int id) {
          object.id = id;
        },
        objectToFB: (BalanceEntity object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.walletId);
          fbb.addInt64(2, object.confirmed);
          fbb.addInt64(3, object.unconfirmed);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final walletIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final confirmedParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final unconfirmedParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = BalanceEntity(
              walletId: walletIdParam,
              confirmed: confirmedParam,
              unconfirmed: unconfirmedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    BlockHeaderEntity: obx_int.EntityDefinition<BlockHeaderEntity>(
        model: _entities[3],
        toOneRelations: (BlockHeaderEntity object) => [],
        toManyRelations: (BlockHeaderEntity object) => {},
        getId: (BlockHeaderEntity object) => object.id,
        setId: (BlockHeaderEntity object, int id) {
          object.id = id;
        },
        objectToFB: (BlockHeaderEntity object, fb.Builder fbb) {
          final headerOffset = fbb.writeString(object.header);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.height);
          fbb.addInt64(2, object.timestamp);
          fbb.addOffset(3, headerOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final heightParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final timestampParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final headerParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = BlockHeaderEntity(
              heightParam, timestampParam, headerParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    CustomIdEntity: obx_int.EntityDefinition<CustomIdEntity>(
        model: _entities[4],
        toOneRelations: (CustomIdEntity object) => [],
        toManyRelations: (CustomIdEntity object) => {},
        getId: (CustomIdEntity object) => object.id,
        setId: (CustomIdEntity object, int id) {
          object.id = id;
        },
        objectToFB: (CustomIdEntity object, fb.Builder fbb) {
          final entityNameOffset = fbb.writeString(object.entityName);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, entityNameOffset);
          fbb.addInt64(2, object.customId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final entityNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final customIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object = CustomIdEntity(entityNameParam, customIdParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TransactionEntity: obx_int.EntityDefinition<TransactionEntity>(
        model: _entities[5],
        toOneRelations: (TransactionEntity object) => [],
        toManyRelations: (TransactionEntity object) => {},
        getId: (TransactionEntity object) => object.id,
        setId: (TransactionEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TransactionEntity object, fb.Builder fbb) {
          final txHashOffset = fbb.writeString(object.txHash);
          final txStringOffset = fbb.writeString(object.txString);
          final prevTxStringListOffset = fbb.writeList(object.prevTxStringList
              .map(fbb.writeString)
              .toList(growable: false));
          final memoOffset = fbb.writeString(object.memo);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.walletId);
          fbb.addOffset(2, txHashOffset);
          fbb.addOffset(3, txStringOffset);
          fbb.addInt64(4, object.timestamp);
          fbb.addInt64(5, object.height);
          fbb.addOffset(6, prevTxStringListOffset);
          fbb.addOffset(7, memoOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final walletIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final txHashParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final txStringParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final prevTxStringListParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 16, []);
          final timestampParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final heightParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final object = TransactionEntity(
              walletId: walletIdParam,
              txHash: txHashParam,
              txString: txStringParam,
              prevTxStringList: prevTxStringListParam,
              timestamp: timestampParam,
              height: heightParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..memo = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '');

          return object;
        }),
    UtxoEntity: obx_int.EntityDefinition<UtxoEntity>(
        model: _entities[6],
        toOneRelations: (UtxoEntity object) => [],
        toManyRelations: (UtxoEntity object) => {},
        getId: (UtxoEntity object) => object.id,
        setId: (UtxoEntity object, int id) {
          object.id = id;
        },
        objectToFB: (UtxoEntity object, fb.Builder fbb) {
          final txHashOffset = fbb.writeString(object.txHash);
          final txStringOffset = fbb.writeString(object.txString);
          final derivationPathOffset = fbb.writeString(object.derivationPath);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.walletId);
          fbb.addInt64(2, object.amount);
          fbb.addOffset(3, txHashOffset);
          fbb.addInt64(4, object.index);
          fbb.addOffset(5, txStringOffset);
          fbb.addOffset(6, derivationPathOffset);
          fbb.addInt64(7, object.timestamp);
          fbb.addInt64(8, object.height);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final walletIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final txHashParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final amountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final indexParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final txStringParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final derivationPathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, '');
          final timestampParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final heightParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final object = UtxoEntity(
              walletId: walletIdParam,
              txHash: txHashParam,
              amount: amountParam,
              index: indexParam,
              txString: txStringParam,
              derivationPath: derivationPathParam,
              timestamp: timestampParam,
              height: heightParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AddressBookEntity] entity fields to define ObjectBox queries.
class AddressBookEntity_ {
  /// See [AddressBookEntity.id].
  static final id =
      obx.QueryIntegerProperty<AddressBookEntity>(_entities[0].properties[0]);

  /// See [AddressBookEntity.walletId].
  static final walletId =
      obx.QueryIntegerProperty<AddressBookEntity>(_entities[0].properties[1]);

  /// See [AddressBookEntity.usedReceiveIndex].
  static final usedReceiveIndex =
      obx.QueryIntegerProperty<AddressBookEntity>(_entities[0].properties[2]);

  /// See [AddressBookEntity.usedChangeIndex].
  static final usedChangeIndex =
      obx.QueryIntegerProperty<AddressBookEntity>(_entities[0].properties[3]);

  /// See [AddressBookEntity.maxReceiveIndex].
  static final maxReceiveIndex =
      obx.QueryIntegerProperty<AddressBookEntity>(_entities[0].properties[4]);

  /// See [AddressBookEntity.maxChangeIndex].
  static final maxChangeIndex =
      obx.QueryIntegerProperty<AddressBookEntity>(_entities[0].properties[5]);

  /// see [AddressBookEntity.receiveList]
  static final receiveList =
      obx.QueryBacklinkToMany<AddressEntity, AddressBookEntity>(
          AddressEntity_.receiveBook);

  /// see [AddressBookEntity.changeList]
  static final changeList =
      obx.QueryBacklinkToMany<AddressEntity, AddressBookEntity>(
          AddressEntity_.changeBook);
}

/// [AddressEntity] entity fields to define ObjectBox queries.
class AddressEntity_ {
  /// See [AddressEntity.id].
  static final id =
      obx.QueryIntegerProperty<AddressEntity>(_entities[1].properties[0]);

  /// See [AddressEntity.address].
  static final address =
      obx.QueryStringProperty<AddressEntity>(_entities[1].properties[1]);

  /// See [AddressEntity.isUsed].
  static final isUsed =
      obx.QueryBooleanProperty<AddressEntity>(_entities[1].properties[2]);

  /// See [AddressEntity.derivationPath].
  static final derivationPath =
      obx.QueryStringProperty<AddressEntity>(_entities[1].properties[3]);

  /// See [AddressEntity.index].
  static final index =
      obx.QueryIntegerProperty<AddressEntity>(_entities[1].properties[4]);

  /// See [AddressEntity.amount].
  static final amount =
      obx.QueryIntegerProperty<AddressEntity>(_entities[1].properties[5]);

  /// See [AddressEntity.receiveBook].
  static final receiveBook =
      obx.QueryRelationToOne<AddressEntity, AddressBookEntity>(
          _entities[1].properties[6]);

  /// See [AddressEntity.changeBook].
  static final changeBook =
      obx.QueryRelationToOne<AddressEntity, AddressBookEntity>(
          _entities[1].properties[7]);
}

/// [BalanceEntity] entity fields to define ObjectBox queries.
class BalanceEntity_ {
  /// See [BalanceEntity.id].
  static final id =
      obx.QueryIntegerProperty<BalanceEntity>(_entities[2].properties[0]);

  /// See [BalanceEntity.walletId].
  static final walletId =
      obx.QueryIntegerProperty<BalanceEntity>(_entities[2].properties[1]);

  /// See [BalanceEntity.confirmed].
  static final confirmed =
      obx.QueryIntegerProperty<BalanceEntity>(_entities[2].properties[2]);

  /// See [BalanceEntity.unconfirmed].
  static final unconfirmed =
      obx.QueryIntegerProperty<BalanceEntity>(_entities[2].properties[3]);
}

/// [BlockHeaderEntity] entity fields to define ObjectBox queries.
class BlockHeaderEntity_ {
  /// See [BlockHeaderEntity.id].
  static final id =
      obx.QueryIntegerProperty<BlockHeaderEntity>(_entities[3].properties[0]);

  /// See [BlockHeaderEntity.height].
  static final height =
      obx.QueryIntegerProperty<BlockHeaderEntity>(_entities[3].properties[1]);

  /// See [BlockHeaderEntity.timestamp].
  static final timestamp =
      obx.QueryIntegerProperty<BlockHeaderEntity>(_entities[3].properties[2]);

  /// See [BlockHeaderEntity.header].
  static final header =
      obx.QueryStringProperty<BlockHeaderEntity>(_entities[3].properties[3]);
}

/// [CustomIdEntity] entity fields to define ObjectBox queries.
class CustomIdEntity_ {
  /// See [CustomIdEntity.id].
  static final id =
      obx.QueryIntegerProperty<CustomIdEntity>(_entities[4].properties[0]);

  /// See [CustomIdEntity.entityName].
  static final entityName =
      obx.QueryStringProperty<CustomIdEntity>(_entities[4].properties[1]);

  /// See [CustomIdEntity.customId].
  static final customId =
      obx.QueryIntegerProperty<CustomIdEntity>(_entities[4].properties[2]);
}

/// [TransactionEntity] entity fields to define ObjectBox queries.
class TransactionEntity_ {
  /// See [TransactionEntity.id].
  static final id =
      obx.QueryIntegerProperty<TransactionEntity>(_entities[5].properties[0]);

  /// See [TransactionEntity.walletId].
  static final walletId =
      obx.QueryIntegerProperty<TransactionEntity>(_entities[5].properties[1]);

  /// See [TransactionEntity.txHash].
  static final txHash =
      obx.QueryStringProperty<TransactionEntity>(_entities[5].properties[2]);

  /// See [TransactionEntity.txString].
  static final txString =
      obx.QueryStringProperty<TransactionEntity>(_entities[5].properties[3]);

  /// See [TransactionEntity.timestamp].
  static final timestamp =
      obx.QueryIntegerProperty<TransactionEntity>(_entities[5].properties[4]);

  /// See [TransactionEntity.height].
  static final height =
      obx.QueryIntegerProperty<TransactionEntity>(_entities[5].properties[5]);

  /// See [TransactionEntity.prevTxStringList].
  static final prevTxStringList =
      obx.QueryStringVectorProperty<TransactionEntity>(
          _entities[5].properties[6]);

  /// See [TransactionEntity.memo].
  static final memo =
      obx.QueryStringProperty<TransactionEntity>(_entities[5].properties[7]);
}

/// [UtxoEntity] entity fields to define ObjectBox queries.
class UtxoEntity_ {
  /// See [UtxoEntity.id].
  static final id =
      obx.QueryIntegerProperty<UtxoEntity>(_entities[6].properties[0]);

  /// See [UtxoEntity.walletId].
  static final walletId =
      obx.QueryIntegerProperty<UtxoEntity>(_entities[6].properties[1]);

  /// See [UtxoEntity.amount].
  static final amount =
      obx.QueryIntegerProperty<UtxoEntity>(_entities[6].properties[2]);

  /// See [UtxoEntity.txHash].
  static final txHash =
      obx.QueryStringProperty<UtxoEntity>(_entities[6].properties[3]);

  /// See [UtxoEntity.index].
  static final index =
      obx.QueryIntegerProperty<UtxoEntity>(_entities[6].properties[4]);

  /// See [UtxoEntity.txString].
  static final txString =
      obx.QueryStringProperty<UtxoEntity>(_entities[6].properties[5]);

  /// See [UtxoEntity.derivationPath].
  static final derivationPath =
      obx.QueryStringProperty<UtxoEntity>(_entities[6].properties[6]);

  /// See [UtxoEntity.timestamp].
  static final timestamp =
      obx.QueryIntegerProperty<UtxoEntity>(_entities[6].properties[7]);

  /// See [UtxoEntity.height].
  static final height =
      obx.QueryIntegerProperty<UtxoEntity>(_entities[6].properties[8]);
}
